In [62]:
# Pandas is a data manipuation and analysis library for Python. Here I aliased with pd
import pandas as pd

In [36]:
# I used df variable to read the csv file
# The csv file is Salary_Data.csv
# The csv file is in the same directory as this script
# The csv file contains the salary data of employees
df = pd.read_csv("Salary_Data.csv")

In [37]:
#Display the table Salary_Data.csv (visualize the data)
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [56]:
#extracted Years of Experience column from the csv file. X capitial is because it can contain multiple columns
# double square brackets is used [table["column_name"]]
# if i need more columens, i can add like X = df[["colum_1", "colum_2"]]

X= df[["YearsExperience"]]

#display Years of experience from the csv file
X

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [39]:
#extracted Salary col from the csv file. 
# double square brackets is used [table["column_name"]]


y = df[["Salary"]]
#display Salary from the csv file
y

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [ ]:
#importing train_test_split from sklearn.model_selection library (only to save memory)
#it is used t split the dataset to training and testing
from sklearn.model_selection import train_test_split


#given the parameters X(input) and y(output), test_size=0.3 (30% of th data), random state is some random number, 
# at this point not sure exactly, i can check the internet
#4 outputs are returned and assigned to 4 variables: X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3, random_state=42)

In [43]:
#importing LinearRegression from sklearn.linear_model library
#Since the problem statemnent has clear requirement and output is available and in figures, used LinearRegression
from sklearn.linear_model import LinearRegression

# Creating a linear regression model and assign to variable name "model"
model  = LinearRegression()

# Fitting the model to the training data
model.fit(X_train, y_train)

LinearRegression()

In [58]:
#Getting weight value, that is nothing but the slope of the line using model.coef_ and assinging value to weight variable. 
weight = model.coef_
#display the out put of slope (weight variable)
weight

array([[9339.08172382]])

In [45]:
#getting the bias value using model.intercept_ and assigning value to bias variable
bias = model.intercept_

#bias (original value) is the y intercept of the line
bias

array([25918.43833489])

In [29]:
#predicting the output of X_test using the model and assigning value to y_pred variable
y_pred = model.predict(X_test)

In [59]:
#importing r2_score from sklearn.metrics library
from sklearn.metrics import r2_score
#checking preducted value is same as the original value
r_score = r2_score(y_test, y_pred)

In [49]:
#saving the file using pickle library
import pickle 

#created a file name "finalized_mode_linear.sav" and assigned to filename variable
filename = "finalized_mode_linear.sav"

In [50]:
#saveed the file using pickle.dump function as write binary mode
pickle.dump(model,open(filename, 'wb'))

In [60]:
#Loading the saved model using pickle.load function
loaded_model=pickle.load(open(filename, 'rb'))
#predicting the out put from the loaded model using filename.load(open file, read binary mode)
#save the predicted value to result variable
result = loaded_model.predict([[5]])

/Users/aanvazhapilly/Aan_python/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [61]:
#display the predicted value of the loaded model
result

array([[72613.84695397]])